monitor=,preferred,auto,1

env = XCURSOR_THEME.Bibata-Modern-Ice
env = XCURSOR_SIZE,20
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,20
env = QT_QPA_PLATEFORTHEME,qt5ct

exec-once = swww-daemon
exec-once = swww img ~/Pictures/wallpapers/kuromi.png
exec-once = waybar
exec-once = mako
exec-once = eww daemon
exec-once = hypridle
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentification-agent-1
exec-once = hyprpaper
exec_once = kitty
exec-once = wl-paste --match cliphist store
exec-once = hyprpm reload -n
exec-once = mp-applet --indicator
exec-once = hyprctl setcursor Bibata-Modern-Ice 20

windowrule = match:class ^(.*)$, float on

input {
	kb_layout = fr
	follow_mouse = 1
	touchpad {
		natural_scroll = true
	}
}

general {
	gaps_in = 5
	gaps_out = 12
	border_size = 2
	col.active_border = rgba(c084fcee) rgba(a855f7ee) 45deg
	col.inactive_border = rgba(3a3a3aaa)
	layout = dwindle
	resize_on_border = true
}

decoration {
	rounding = 14
	blur {
		enabled = true
		size = 6
		passes = 3
	}
	shadow {
		enabled = true
		range = 20
		color = rgba(1a1a1aee)
	}
}

animations {
	enabled = true
	bezier = smooth, 0.25, 0.1, 0.25, 1
	animation = windows, 1, 5, smooth
	animation = fade, 1, 5, smooth
	animation = workspaces, 1, 5, smooth
}

dwindle {
	preserve_split = true
}

plugin {
    hyprbars {
        bar_height = 28
        bar_color = rgba(1e152bcc)
        col.text = rgba(e5d4ffff)
        bar_text_size = 11
        bar_text_font = JetBrainsMono Nerd Font
        bar_text_align = center
        bar_buttons_alignment = left
        bar_padding = 8
        bar_button_padding = 5
        icon_on_hover = true

        hyprbars-button = rgb(28c840), 14, 󰖰, hyprctl dispatch movetoworkspacesilent special:minized
        hyprbars-button = rgb(febc2e), 14, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(ff5f57), 14, 󰖭, hyprctl dispatch killactive

        on_double_click = hyprctl dispatch fullscreen 1
    }
}

$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, Q, killactive
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, L, exec, hyprlock
bind = $mainMod SHIFT, E, exec, eww open power-menu
bind = $mainMod, W, exec, ~/.config/hypr/scripts/change-wallpaper.sh
bind = $mainMod, F, exec, firefox


bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3 

bind = $mainMod, left, movefocus, 1
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d


bind = $mainMod SHIFT, left, movewindow, 1
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d


bind = $mainMod, G, fullscreen, 0
bind = $mainMod, V, togglefloating


bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1


binde = $mainMod CTRL, right, resizeactive, 30 0 
binde = $mainMod CTRL, left, resizeactive, -30 0
binde = $mainMod CTRL, up, resizeactive, 0 -30
binde = $mainMod CTRL, down, resizeactive, 0 30


bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, movewindow

bindel = ,XF86AudioRaiseVolume, exec, pamixer -i 5
bindel = ,XF86AudioLowerVolume, exec, pamixer -d 5
bindel = ,XF86AudioMute, exec, pamixer -t
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-
bindl = ,XF86AudioPlay, exec, playerctl play-pause
bindl = ,XF86AudioNext, exec, playerctl next
bindl = ,XF86AudioPrev, exec, playerctl previous

bind = , PRINT, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod, PRINT, exec, grim - | wl-copy
bind = $mainMod, C, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

bind = $mainMod, E, exec, thunar
